name: Docs from PR

on:
  pull_request:
    types: [closed]

jobs:
  sync-docs:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout docs repository
        uses: actions/checkout@v3
        with:
          repository: Rita-Tavares/demo-docs-repo
          token: ${{ secrets.DOCS_REPO_TOKEN }}
          path: docs-repo

      - name: Copy updated content
        run: |
          mkdir -p docs-repo/new-docs
          rsync -av --exclude='.git' ./ docs-repo/new-docs/

      - name: Commit and push changes to docs repo
        run: |
          cd docs-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b docs-update-${{ github.event.pull_request.number }}
          git add .
          git commit -m "Docs: update from PR #${{ github.event.pull_request.number }}" || echo "No changes to commit"
          git push origin docs-update-${{ github.event.pull_request.number }}

      - name: Create pull request in docs repo
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.DOCS_REPO_TOKEN }}
          path: docs-repo
          title: "Docs: update from PR #${{ github.event.pull_request.number }}"
          commit-message: "Docs: update from PR #${{ github.event.pull_request.number }}"
